{
 "title": "Zabbix Host Status v2",
 "description": "Status of a server monitored by zabbix agent",
 "tags": [
  "zabbix",
  "agent",
  "system"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "group", "query": "*" },
   { "name": "host", "query": "$group.*" },
   {
    "name": "disk",
    "label": "disk",
    "query": "$group.$host.Disk Performance.*"
   },
   {
    "name": "netIf",
    "label": "NetIf",
    "query": "$group.$host.Network interfaces.*"
   },
   { "name": "fs", "label": "fs", "query": "$group.$host.Filesystems.*" }
  ]
 },
 "panels": [
  {
   "title": "Notes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "pve-b3",
     "type": "text",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
     "content": "## disks\r\n\r\n| name | type           | (lvm)mounts | non-system data                                                                             | comments |\r\n|------|----------------|-------------|---------------------------------------------------------------------------------------------|----------|\r\n| sda  | ssd hw raid1   | /           | docker: svn, teamcity 2k18, jfrog artifactory-oss, teampass                                                                                         |          |\r\n| sdb  | sata hw raid10 | /mnt/svn    | svn                                                                                         |          |\r\n| sdc  | sata hw raid1  | /mnt/data   | nfs4 shares: bp-symstore  |          |\r\n|||                                   |smb: shares:  versions  pdb-symstore switch-symstore||\r\n\r\n\r\n## network\r\nbond0 : 2Gb bond of eno2, eno3 //192.168.20.245\r\n\r\nens2f0: 10Gb //172.16.0.3\r\n"
    },
    {
     "title": "pve-macos",
     "type": "text",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 1 },
     "content": "## disks\r\n\r\n| name     | type           | (zfs)pools  | non-system data                                                                             | comments |\r\n|----------|----------------|-------------|---------------------------------------------------------------------------------------------|----------|\r\n| nvme0n1  | ssd (mii)      | /data       | nfs shares: build_test                                                                      |          |\r\n\r\n\r\n## network\r\nvmbr1: 10Gib //172.16.0.205\r\nvmbr0: //192.168.20.188\r\n\r\n\r\n"
    }
   ]
  },
  { "title": "common stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  { "title": "Host Information", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 }, "content": "## $group - $host" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "alias": "System uptime",
     "application": {
      "filter": "",
      "isRegex": false,
      "name": "General",
      "style": {}
     },
     "downsampleFunction": { "name": "max", "value": "max" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "System uptime",
      "isRegex": false,
      "name": "System uptime",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Processor load (1 min average per core)",
     "application": {
      "filter": "",
      "isRegex": false,
      "name": "Performance",
      "style": {}
     },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Processor load (1 min average per core)",
      "isRegex": false,
      "name": "Processor load (1 min average per core)",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Available memory",
     "application": { "name": "Memory" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Available memory",
      "isRegex": false,
      "name": "Available memory",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Number of processes",
     "application": { "name": "Processes" },
     "downsampleFunction": { "name": "avg", "value": "avg" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Number of processes",
      "isRegex": false,
      "name": "Number of processes",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logged in Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Number of logged in users",
     "application": { "name": "Security" },
     "downsampleFunction": { "name": "max", "value": "max" },
     "group": {
      "filter": "$group",
      "isRegex": false,
      "name": "$group",
      "style": {},
      "templated": true
     },
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "host": {
      "filter": "$host",
      "isRegex": false,
      "name": "$host",
      "style": {},
      "templated": true
     },
     "item": {
      "filter": "Number of logged in users",
      "isRegex": false,
      "name": "Number of logged in users",
      "style": {}
     },
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "fs stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "free disk space on $fs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "repeat": "fs",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "In eth0",
       "application": { "filter": "Filesystems", "name": "Network interfaces" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "Free disk space on $fs",
        "isRegex": false,
        "name": "Incoming network traffic on eth0",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Network stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "$netIf in/out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "repeat": "netIf",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "In eth0",
       "application": { "filter": "Network interfaces", "name": "Network interfaces" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "/.* network traffic on $netIf/",
        "isRegex": false,
        "name": "Incoming network traffic on eth0",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "$disk stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "$disk read/write MiB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "In eth0",
       "application": { "filter": "Disk Performance", "name": "Network interfaces" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "Disk:$disk Read",
        "isRegex": false,
        "name": "Incoming network traffic on eth0",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "In eth0",
       "application": { "filter": "Disk Performance", "name": "Network interfaces" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "Disk:$disk Write",
        "isRegex": false,
        "name": "Incoming network traffic on eth0",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "$disk iops + Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 11, "y": 8 },
     "yaxes": [
      { "format": "none", "label": "iops" }
     ],
     "targets": [
      {
       "alias": "In eth0",
       "application": { "filter": "Disk Performance", "name": "Network interfaces" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "iops" ],
         "text": "setAlias(iops)"
        },
        {
         "def": {
          "category": "Aggregate",
          "defaultParams": [],
          "name": "sumSeries",
          "params": []
         },
         "params": [],
         "text": "sumSeries()"
        }
       ],
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "/Disk:$disk .* Ops/",
        "isRegex": false,
        "name": "Incoming network traffic on eth0",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "In eth0",
       "application": { "filter": "Disk Performance", "name": "Network interfaces" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Utilization" ],
         "text": "setAlias(Utilization)"
        }
       ],
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "/Disk:$disk Utilization/",
        "isRegex": false,
        "name": "Incoming network traffic on eth0",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "$disk read/wirte ops",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Disk Performance" },
       "group": { "filter": "$group" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "$host" },
       "item": { "filter": "/Disk:$disk .* Ops/" },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "cpu/mem stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "iowait",
       "application": { "name": "CPU" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "iowait" ],
         "text": "setAlias(iowait)"
        }
       ],
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "CPU iowait time",
        "isRegex": false,
        "name": "CPU iowait time",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "user",
       "application": { "name": "CPU" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "system" ],
         "text": "setAlias(system)"
        }
       ],
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "CPU system time",
        "isRegex": false,
        "name": "CPU user time",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "system",
       "application": { "name": "CPU" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "user" ],
         "text": "setAlias(user)"
        }
       ],
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "CPU user time",
        "isRegex": false,
        "name": "CPU system time",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "idle",
       "application": { "name": "CPU" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "steal" ],
         "text": "setAlias(steal)"
        }
       ],
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "CPU steal time",
        "isRegex": false,
        "name": "CPU idle time",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "idle",
       "application": { "name": "CPU" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "interrupt" ],
         "text": "setAlias(interrupt)"
        }
       ],
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "CPU interrupt time",
        "isRegex": false,
        "name": "CPU idle time",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "idle",
       "application": { "name": "CPU" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "nice" ],
         "text": "setAlias(nice)"
        }
       ],
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "CPU nice time",
        "isRegex": false,
        "name": "CPU idle time",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "idle",
       "application": { "name": "CPU" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "idle" ],
         "text": "setAlias(idle)"
        }
       ],
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "CPU idle time",
        "isRegex": false,
        "name": "CPU idle time",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Available memory",
       "application": { "name": "Memory" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "/.*memory/",
        "isRegex": false,
        "name": "Available memory",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Free Swap %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "Free swap space in %",
       "application": { "name": "Memory" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "Free swap space in %",
        "isRegex": false,
        "name": "Free swap space in %",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "cpu load avg per 1 min.",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "1 min average",
       "application": { "name": "Performance" },
       "downsampleFunction": { "name": "avg", "value": "avg" },
       "group": {
        "filter": "$group",
        "isRegex": false,
        "name": "$group",
        "style": {},
        "templated": true
       },
       "groupBy": [
        { "params": [ "auto" ], "type": "time" }
       ],
       "host": {
        "filter": "$host",
        "isRegex": false,
        "name": "$host",
        "style": {},
        "templated": true
       },
       "item": {
        "filter": "Processor load (1 min average per core)",
        "isRegex": false,
        "name": "Processor load (1 min average per core)",
        "style": {}
       },
       "options": {
        "showDisabledItems": false
       },
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}